<?php

$_ADDONLANG['incorrect']='Your code was incorrect.';
$_ADDONLANG['enterCodeNote']='Please enter the code generated by your mobile application.';
$_ADDONLANG['backupCodeInfo']='Login via Backup Code Successful. Backup Codes are valid once only. It will now be reset. ';
$_ADDONLANG['newBackupCodeNote']='Your New Backup Code is';
$_ADDONLANG['enterCode']='Enter your code';
$_ADDONLANG['btnLogin']='Validate Login';
$_ADDONLANG['enterEmCode']='Enter your emergency code';
$_ADDONLANG['emLogin']='Emergency Login';
$_ADDONLANG['lostDevice']='Lost your mobile device?';
$_ADDONLANG['inactive']='Two-Factor Authentication support is currently disabled.';
$_ADDONLANG['disabled']='Two-Factor Authentication is currently disabled.';
$_ADDONLANG['btnEnable']='Enable Two-Factor Authentication';
$_ADDONLANG['scanNote']='Please scan this QR code with your mobile authenticator app.';
$_ADDONLANG['unableScan']='If you are unable to scan, use this secret:';
$_ADDONLANG['verify']='Verify Code';
$_ADDONLANG['recomApp']='Recommended App';
$_ADDONLANG['enabled']='Two-Factor Authentication is currently enabled.';
$_ADDONLANG['emCode']='Your emergency code is';
$_ADDONLANG['emCodeNote']='You can use this if you ever lose your mobile device.';
$_ADDONLANG['btnSecret']='View Secret';
$_ADDONLANG['emCodeNote2']='Write this down, because it won\'t be displayed again.';
$_ADDONLANG['btnDisable']='Disable Two-Factor Authentication';
$_ADDONLANG['note']='Note: Any sub-users with access to your account will need to supply a two-factor authentication token.';

?>
