{include file="$template/pageheader.tpl" title="$pagetitle"}

<div class="logincontainer" style="text-align:center; width:400px">

{if $incorrect}
	<div class="alert alert-error">Your code was incorrect.</div>
{/if}

{if $login}
	<p>Please enter the code generated by your mobile application.</p><br /><br />
	<form method="post" action="{$modulelink}">
	<input type="hidden" name="action" value="login" />
	<input type="text" name="code" placeholder="Enter your code" /><br /><br />
	<button type="submit" class="btn btn-primary">Validate Login</button>
	</form><br /><br />
	<div>
		<button class="btn" onclick="this.parentNode.innerHTML = '<form method=\'post\' action=\'{$modulelink}\'><input type=\'hidden\' name=\'action\' value=\'login\' /><input type=\'text\' name=\'emergencycode\' placeholder=\'Enter your emergency code\' /><br /><br /><button type=\'submit\' class=\'btn btn-primary\'>Emergency Login</button></form>'">Lost your mobile device?</button>
	</div>
{elseif !$enable_clients}
	<div class="alert alert-error">Two-factor authentication support is currently disabled.</div>
{elseif !$active}
	{if !$verify}
		<p>Two-Factor Authentication is currently disabled.</p><br /><br />
		<form method="post" action="{$modulelink}">
		<input type="hidden" name="action" value="enable" />
		<button type="submit" class="btn btn-primary">Enable Two-Factor Authentication</button>
		</form>
	{else}
		<p>Please scan this QR code with your mobile authenticator app.</p><br /><br />
		<img src="{$modulelink}&qr=1&secret={$secret}" /><br /><br />
		<p>If you are unable to scan, use this secret:<br />{$secret}</p><br /><br />
		<form method="post" action="{$modulelink}">
		<input type="hidden" name="action" value="verify" />
		<input type="hidden" name="secret" value="{$secret}" />
		<input type="text" name="code" placeholder="Enter your code" /><br /><br />
		<button type="submit" class="btn btn-primary">Verify Code</button>
		</form><br /><br />
		<p>Recommended App: Google Authenticator<br />(<a href="https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8" target="_blank">iOS</a> / <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en" target="_blank">Android</a>)</p>
	{/if}
{else}
	<p>Two-Factor Authentication is currently enabled.</p><br />
	{if $allow_secret_review}
		<div>
			<button class="btn btn-primary" onclick="this.parentNode.innerHTML = '<img src=\'{$modulelink}&qr=1&secret={$secret}\' /><br /><br /><p>If you are unable to scan, use this secret:<br />{$secret}</p><br /><br />{if !$firstactivation}<p>Your emergency code is: {$emergencycode}<br /><br />You can use this if you ever lose your mobile device.</p><br /><br />{/if}'">View Secret</button><br /><br />
		</div>
	{/if}
	{if $firstactivation}
		<p>Your emergency code is: {$emergencycode}<br /><br />You can use this if you ever lose your mobile device.{if !$allow_secret_review} Write this down, because it won't be displayed again.{/if}</p><br />
	{/if}
	<form method="post" action="{$modulelink}">
	<input type="hidden" name="action" value="disable" />
	<button type="submit" class="btn btn-danger">Disable Two-Factor Authentication</button>
	</form><br /><br />
	<p>Note: Any sub-users with access to your account will need to supply a two-factor authentication token.</p>
{/if}

</div>